path:
  - .
  - common
  - includes-core
  - lib
jobs: 10
extensions:
  - php
exclude:
  - .github
  - dev-workspace-cache
  - dist
  - vendor
  - lib/vendor
  - .wordpress-org
  - .node_modules
  - languages
