name: devworkspace_statuses_free
version: "3"
services:
    terminal:
        build: .
        image: publishpress/dev-workspace-terminal:statuses-free-2
        command: ["zsh"]
        stdin_open: true
        tty: true
        working_dir: "/project"
        volumes:
            - ../../:/project
            - ../cache/.zsh_history:/root/.zsh_history
            - ../cache/.bash_history:/root/.bash_history
            - ../cache/.npm/_cacache:/root/.npm/_cacache
            - ../cache/.npm/_logs:/root/.npm/_logs
            - ../cache/.oh-my-zsh/log:/root/.oh-my-zsh/log
            - ../cache/.composer/cache:/root/.composer/cache
            - ../cache/.composer/auth.json:/root/.composer/auth.json
            - /var/run/docker.sock:/var/run/docker.sock
            - html:/var/www/html
            - db:/var/lib/mysql
        extra_hosts:
            - "dockerhost:${DOCKER_HOST_IP}"
        environment:
            - DOCKER_HOST_IP=${DOCKER_HOST_IP}

    web:
        image: wordpress:6.3.1-apache
        restart: always
        ports:
            - "8081:80"
        environment:
            WORDPRESS_DB_HOST: db
            WORDPRESS_DB_USER: statuses_dev
            WORDPRESS_DB_PASSWORD: statuses_dev
            WORDPRESS_DB_NAME: wp_statuses_dev
        volumes:
            - html:/var/www/html
        depends_on:
            - db

    db:
        image: mariadb:10.5.8
        restart: always
        ports:
            - "3310:3306"
        environment:
            MYSQL_ROOT_PASSWORD: statuses_dev
            MYSQL_DATABASE: wp_statuses_dev
            MYSQL_USER: statuses_dev
            MYSQL_PASSWORD: statuses_dev
        volumes:
            - db:/var/lib/mysql

volumes:
    html:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ../cache/html
    db:
