#!/usr/bin/env bash

# Create empty cache files if not exists.
[[ -d cache/html ]] || mkdir -p cache/html

DOCKER_HOST_IP=$(php ./scripts/getip)
export DOCKER_HOST_IP

is_online() {
    echo -e "GET http://google.com HTTP/1.0\n\n" | nc google.com 80 > /dev/null 2>&1

    if [ $? -eq 0 ]; then
        echo 1
    else
        echo 0
    fi
}

pull_image() {
    docker compose -f docker/compose.yaml pull
}

run_wp_service() {
    DOCKER_HOST_IP=$DOCKER_HOST_IP docker compose -f docker/compose.yaml up web "$@"
}

if [ "$(is_online)" -eq 1 ]; then
    # Check and update the image if needed, but do not display anything if there is any argument passed.
    if [[ $# -eq 0 ]]; then
        echo "Checking if the image is up to date..."
        pull_image
    else
        pull_image > /dev/null 2>&1
    fi
else
    if [[ $# -eq 0 ]]; then
        echo "Offline mode detected, ignoring image update."
    fi
fi

run_wp_service "$@"
