name: Code checks
on:
  pull_request:
    branches:
      - '*'

  workflow_call:

  workflow_dispatch:

jobs:
  check:
    # v2.0.0
    uses: publishpress/github-workflows/.github/workflows/code-check.yml@master
