name: Code checks
on:
  push:
    branches:
      - 'master'

  workflow_call:

  workflow_dispatch:

jobs:
  check:
    # v2.0.0
    uses: publishpress/github-workflows/.github/workflows/deploy-free-assets.yml@master
